name: clockboxci
on:
  merge_group:
    branches: [main]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      - name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v2.1.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockboxtst:latest